name: TV Guide

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  tvguide-update:
    name: Update TV Guide

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: tvguide

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run EPG Downloader
      run: |
        python epg_downloader.py ustvgo.for-dark-bg.xml \
          --create-archive \
          --base-url https://raw.githubusercontent.com/interlark/ustvgo-iptv/tvguide

        python epg_downloader.py ustvgo.for-light-bg.xml \
          --create-archive \
          --icons-for-light-bg \
          --base-url https://raw.githubusercontent.com/interlark/ustvgo-iptv/tvguide

    - name: Get current time
      id: time
      run: echo "::set-output name=time::$(date -u +'%Y-%m-%d %H:%M UTC')"

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'TV Guide update ${{ steps.time.outputs.time }}'
